# Based on https://github.com/marketplace/actions/build-docker-image-and-push-to-ghcr-docker-hub-or-aws-ecr
# With updated commit refs below
name: Publish to GHCR.io
 
on:
  push:
    branches:
      - '*'  # Runs on all branches
    tags-ignore:
      - '*'  # Ignores pushes to tags

env:
  REGISTRY: ghcr.io

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      deployments: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.6.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: Sanitize repo slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ env.REGISTRY }}/${{ github.repository }}'.toLowerCase()

      - name: Extract SemVer Tag
        id: semver
        run: |
          TAG=$(git describe --tags --match "v*" --abbrev=0 || echo "")
          if [[ "$TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "full=${TAG}" >> $GITHUB_OUTPUT
            echo "major_minor=v${BASH_REMATCH[1]}.${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
            echo "major=v${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ steps.repo_slug.outputs.result }}
          tags: |
            # Latest tag if on default branch (main/master)
            type=raw,value=latest,enable={{is_default_branch}}
            # Date tag in YYYYMMDD format
            type=raw,value={{date 'YYYYMMDD'}}
            # Branch name (only for non-default branches)
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
            # Branch name with YYYYMMDD if not on default branch
            type=raw,value={{branch}}-{{date 'YYYYMMDD'}},enable=${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
            # Full SHA reference of the commit
            type=sha,format=long,prefix=
            # Semver full version tag
            type=raw,value=${{ steps.semver.outputs.full }},enable=${{ steps.semver.outputs.full != '' }}
            # Semver major.minor version
            type=raw,value=${{ steps.semver.outputs.major_minor }},enable=${{ steps.semver.outputs.major_minor != '' }}
            # Semver major version
            type=raw,value=${{ steps.semver.outputs.major }},enable=${{ steps.semver.outputs.major != '' }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
